# Generated by Django 4.0.2 on 2022-02-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=60)),
            ],
        ),
    ]
